"""`uapp-dash` / `uapp-dash-emit` を **exe なしで**名乗らせる `.cmd` シムを作る。

pip が作る launcher exe は未署名なので、ウイルス対策に隔離・実行ブロックされることがある
（`pip install` は成功したのにコマンドが使えない、という形で出る）。除外に触れない環境では
`python -m uapp_dash …` へ読み替えれば動くが、**申告規約もツール側のラッパーも
`uapp-dash …` と書かれている**ため、読み替えを全員に徹底するのは現実的でない。
同じ名前で呼べるようにするのがこのモジュール。

**過去に「exe の隣に同名の `.cmd` を置く」やり方で失敗している**。踏まないための決まり:

1. **exe とは別のディレクトリに置き、PATH の前方に入れる**。`PATHEXT` は同一ディレクトリ内では
   `.exe` を `.cmd` より優先するので、隣に置いても exe が勝つ（隔離されて壊れた exe が居ると詰む）。
   pip の置き場は **`--user` かどうかで変わる**ので、候補は 1 つに決め打ちしない（`_launcher_dirs`）
2. **中身に非 ASCII を書かない**（コメントも）。`.cmd` は OEM コードページで解釈されるため、
   日本語コメントが化けて標準エラーへ漏れ、`doctor` の `--version` 完全一致比較が落ちる。
   埋め込むパスも同じ制約を受けるので、非 ASCII なら 8.3 短縮名へ落とす（`_ascii_path`）
3. **終了コードを明示的に返す**。`exit /b` を付けないと、呼び出し形態によって握り潰される
   （`resource acquire` の終了コード 3 を見落とすと排他機構が無効になる）
4. **シムが呼ぶ `uapp_dash` が、いま `install-shims` を実行している実装と同じであることを
   確かめる**。「import できるか」だけでは足りない ― 素の `python -m uapp_dash` が
   *別の（古い）* site-packages を拾えば、シムは黙って別物を実行する。また cwd や
   `PYTHONPATH` に助けられているだけの状態も見分けられない（シムは別のディレクトリ・
   別のシェルから呼ばれるので、その助けは無い）。**PYTHONPATH を外した中立な cwd で実際に
   解決させ、同じファイルを指したときだけ何も埋めない**（`_resolved_module`）。
   食い違えば `PYTHONPATH` を埋めて、実行される実装を固定する

5. **`.cmd` だけでは危険なので `.ps1` も置く**。`.cmd` は `cmd /c` に解釈されるため、
   **引数の値に `&` `|` `<` `>` `^` `%` が入っていると壊れる**（実測。exe 経由では起きない差）:

       --label "A&B"     -> ラベルは "A" になり、"B" がコマンドとして実行される
       --label "a|b"     -> 引数ごと消え、"b" がコマンドとして実行される
       --label "car^et"  -> "caret" になる
       --label "50%PATH%" -> 環境変数が展開されて別の文字列になる
       --label "a>b"     -> 引数が消え、"b" というファイルが作られる

   **`&` と `|` は単なる文字化けではなく、自由テキスト経由のコマンド実行**である
   （issue 名や依頼文をそのままラベルへ書き写す運用では現実に踏む）。
   `cmd /c` がコマンドラインを読む時点で起きるので `.cmd` の中身では直せない。
   そこで **同じディレクトリに `.ps1` も置く** ― PowerShell は同名の `.cmd` より `.ps1` を
   優先し（pwsh 7 / Windows PowerShell 5.1 の両方で実測）、`@args` で配列のまま渡すので
   これらの文字が無傷で届く。**申告規約もキットのラッパーも PowerShell から呼ぶ**ので、
   実運用の経路はこちらになる。`.cmd` は cmd.exe や `subprocess` からの呼び出し用に残す
   （そこから自由テキストを渡す場合は上の制限が生きる）。
   `!` は呼び出し元が `cmd /V:ON` のときだけ展開されるが、これはシムに限らず exe でも同じ。
   **実行ポリシーで `.ps1` が動かない環境もある**ので、生成後に実走して確かめ、
   動かなければ `.ps1` を置かない（`.cmd` だけの従来構成に倒す）
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
import sysconfig
import tempfile
from pathlib import Path

# 生成するシムと、それが呼ぶモジュール
SHIMS = {"uapp-dash": "uapp_dash", "uapp-dash-emit": "uapp_dash.emit"}

# 中身は **ASCII のみ**（上の決まり 2）。%* で引数をそのまま渡し、終了コードを明示的に返す。
# `setlocal DisableDelayedExpansion` の役目は、**このシム自身の行**が `!` を変数として
# 解釈しないことと、下の環境変数の書き換えを**シムの中だけ**に閉じ込めること
# （呼び手の環境を汚さない）。**引数の中の `!` は守れない** ― 呼び出し元が `cmd /V:ON` なら
# シムに入る前に展開されるため（これはシムに限らず exe でも同じ）。
#
# `-P` は**必須**。`python -m` は**カレントディレクトリを sys.path の先頭**へ置くので、
# 呼び出し先に `uapp_dash\` があれば PYTHONPATH で固定した実装を追い越してそちらが動く
# （実測: 偽パッケージのある場所から呼ぶと `9.9.9-HIJACK` が返った。
# **exe ではこれは起きない**＝シムが持ち込む差）。
# **環境変数（`PYTHONSAFEPATH`）ではなくコマンドラインの `-P` を使う**: `.ps1` は呼び出し元の
# PowerShell の中で動くため、環境変数だと呼び出し元へ漏れうるし、並行して走る runspace と
# 退避・復元が競合して汚染が残る。コマンドラインの引数ならその 1 回の起動にしか効かない。
# `-P` が効かない解釈系（3.10 以前）ではシムを作らない（`_honors_safe_path` が実走で確かめる）
_TEMPLATE = """\
@echo off
setlocal DisableDelayedExpansion
rem Generated by "uapp-dash install-shims". Calls the module directly so that no
rem unsigned launcher exe is involved. Do not add non-ASCII text to this file.
{pythonpath}rem -P keeps the caller's current directory out of sys.path (needs Python 3.11+).
"{python}" -P -m {module} %*
exit /b %ERRORLEVEL%
"""

# 素の `python -m uapp_dash` が**この実装に解決しない**ときだけ差し込む。
# **`if defined` で分ける**のは、`%PYTHONPATH%` が未定義のときに末尾へ `;` が残ると
# 空要素＝カレントディレクトリが sys.path に入ってしまうため（それこそが今回塞ぐ問題）
_PYTHONPATH_LINES = """\
rem Pin the implementation that "install-shims" was run from: a bare
rem "python -m uapp_dash" does not resolve to it (not installed, or another copy wins).
set "UAPP_DASH_PP={pythonpath}"
if defined PYTHONPATH set "UAPP_DASH_PP={pythonpath};%PYTHONPATH%"
set "PYTHONPATH=%UAPP_DASH_PP%"
"""

# PowerShell 版。**PowerShell はこれを同名の `.cmd` より優先する**（pwsh 7 / 5.1 で実測）ので、
# 申告規約やキットのラッパーから呼ぶ実運用の経路はこちらになる。
# 引数は配列のまま渡るため、`&` `|` `<` `>` `^` `%` を含む値も無傷で届く
# （`.cmd` はここで壊れる。それが `.ps1` を併設する理由）。
# **`.ps1` は別プロセスではなく呼び出し元の PowerShell の中で動く**。ここを取り違えると
# 実測で 3 つの穴がある（どれも `.cmd` では起きない、`.ps1` 併設が持ち込む差）:
#   - Windows PowerShell 5.1 は**空文字列の引数を丸ごと落とす**ため、`--label ""` を渡すと
#     以降の値が 1 つずつ違うオプションへ付き、黙って別の意味になる（pwsh 7 は正しい）
#   - `exit $LASTEXITCODE` は、**python を起動できなかったとき 0 を返す**。
#     `$LASTEXITCODE` はセッションの変数なので、**直前のネイティブコマンドの 0 が残る**
#     （`cmd /c exit 0` の直後だと未設定チェックもすり抜ける。pwsh 7 / 5.1 とも実測）。
#     だから呼ぶ直前に自分で `$null` へ戻す
#   - `$env:` への代入は**呼び出し元のセッションに残る**。`PYTHONPATH` は呼ぶたびに増殖し、
#     同じシェルで動かす他の Python（テスト・ビルド）の探索規則まで変えてしまう。
#     `try`/`finally` で必ず元へ戻す（元が未設定なら `$null` を入れて消す）
_PS_TEMPLATE = """\
# Generated by "uapp-dash install-shims". PowerShell prefers this over the .cmd next
# to it, and passes arguments as an array, so values containing & | < > ^ % survive.
# No param() block on purpose: every argument must land in $args untouched, including
# ones that look like parameters (--version, -x) and ones that are empty.
$uappDashArgs = @()
foreach ($uappDashArg in $args) {{
    # Windows PowerShell 5.1 drops empty string arguments entirely, which silently
    # shifts every following value onto the wrong option. '""' survives there.
    if (($uappDashArg -is [string]) -and ($uappDashArg.Length -eq 0) -and
        ($PSVersionTable.PSVersion.Major -lt 6)) {{
        $uappDashArgs += '""'
    }} else {{
        $uappDashArgs += $uappDashArg
    }}
}}
# This script runs inside the caller's PowerShell session, so any environment change
# has to be undone. -P is passed on the command line instead of PYTHONSAFEPATH exactly
# for that reason: a command-line flag cannot leak into the caller or race with a
# parallel runspace. Only the (rarer) PYTHONPATH pin still needs save/restore.
$uappDashOldPythonPath = $env:PYTHONPATH
try {{
{pythonpath}    # $LASTEXITCODE is session state: a previous successful native command leaves 0
    # behind, so "did it run at all" cannot be told apart from "it succeeded".
    # Reset it first; never report a failure to start as success.
    $global:LASTEXITCODE = $null
    & '{python}' -P -m {module} @uappDashArgs
    if ($null -eq $LASTEXITCODE) {{ exit 1 }}
    exit $LASTEXITCODE
}} catch {{
    # A missing/unrunnable interpreter raises a terminating error here. Without this
    # catch the script would unwind past the exit statements and the host would report
    # success. Say what happened and fail.
    # Write to the console directly instead of Write-Error: under
    # $ErrorActionPreference = 'Stop' the latter throws again and skips "exit 1",
    # which makes the exit code depend on the caller's preference.
    [Console]::Error.WriteLine("uapp-dash shim: $_")
    exit 1
}} finally {{
    $env:PYTHONPATH = $uappDashOldPythonPath
}}
"""

_PS_PYTHONPATH_LINES = """\
    # Pin the implementation that "install-shims" was run from.
    $env:PYTHONPATH = if ($env:PYTHONPATH) {{ '{pythonpath};' + $env:PYTHONPATH }} else {{ '{pythonpath}' }}
"""


class ShimError(RuntimeError):
    """シムを作れない理由（呼び手がそのまま人へ見せられる文言にする）。"""


def _escape_percent(text: str) -> str:
    """バッチファイル内でリテラルの `%` を表す形にする。

    `C:\\A%FOO%B\\python.exe` のようなパスをそのまま埋めると `%FOO%` が環境変数として
    展開され、**別のパスを実行する**（実在しなければ空文字に潰れる）。バッチファイルの中では
    `%%` が `%` 1 個になる。
    """
    return text.replace("%", "%%")


def _ascii_path(path: str, *, what: str) -> str:
    """`.cmd` へ埋められる形（ASCII）にする。非 ASCII なら 8.3 短縮名へ落とす。

    `C:\\Users\\山田\\…\\python.exe` は日本語環境ではごく普通に起きる。`.cmd` は OEM
    コードページで解釈されるため非 ASCII を書けず、そのまま `encoding="ascii"` で書くと
    `UnicodeEncodeError` が素通しで飛ぶ（呼び手が人に見せられる文言にならない）。
    Windows の短縮名なら ASCII になるので、それで通す。
    """
    try:
        path.encode("ascii")
        return path
    except UnicodeEncodeError:
        pass
    short = _short_path(path)
    if short:
        try:
            short.encode("ascii")
            return short
        except UnicodeEncodeError:
            pass
    raise ShimError(
        f"{what}に ASCII 以外の文字が含まれており、`.cmd` へ埋め込めません: {path}"
        "（`.cmd` は OEM コードページで解釈されるため化ける。8.3 短縮名も取得できませんでした）。"
        "**ASCII だけのパスに venv を作り、そこへ入れてから作り直してください**"
        "（例: `python -m venv D:\\tools\\uapp-dash-venv`）")


def _short_path(path: str) -> str | None:
    """Windows の 8.3 短縮名（取れなければ None）。"""
    if os.name != "nt":
        return None
    try:
        import ctypes
        from ctypes import wintypes

        get_short = ctypes.windll.kernel32.GetShortPathNameW
        get_short.argtypes = [wintypes.LPCWSTR, wintypes.LPWSTR, wintypes.DWORD]
        get_short.restype = wintypes.DWORD
        size = get_short(path, None, 0)
        if not size:
            return None
        buf = ctypes.create_unicode_buffer(size)
        if not get_short(path, buf, size):
            return None
        return buf.value or None
    except (OSError, AttributeError, ValueError):
        return None


def _resolved_module(python: str) -> str | None:
    """シムと同じ条件で `python -m uapp_dash` を解決させ、掴んだファイルの実パスを返す。

    シムが置かれる条件を**そのまま再現する**のがこの関数の要点:

    - **中立なカレントディレクトリ**で実行する。ソースディレクトリで動かしているだけの状態
      （cwd が sys.path に入っているから通っている）を「通る」と読まない
    - **`PYTHONPATH` を外す**。いま設定されているだけの環境変数は、別のシェルから呼ばれる
      シムには効かない。残したまま試すと「通る」と誤判定して、何も埋めずに壊れたシムを作る

    戻り値を呼び手が**現在の実装と突き合わせる**（`import できるか` だけでは、
    素の Python が古い site-packages を拾っている場合に別物を実行するシムができる）。
    """
    env = {k: v for k, v in os.environ.items() if k != "PYTHONPATH"}
    # **子の標準出力を UTF-8 に固定する**。既定だとコンソールのコードページ（日本語 Windows は
    # cp932）で符号化されるため、インストール先に cp932 で表せない文字が 1 つでもあると
    # 子が UnicodeEncodeError で落ち、「解決不能」と誤判定してしまう（実測）
    env["PYTHONIOENCODING"] = "utf-8"
    code = "import uapp_dash,sys; sys.stdout.write(uapp_dash.__file__ or '')"
    try:
        with tempfile.TemporaryDirectory() as neutral:
            proc = subprocess.run([python, "-c", code], cwd=neutral, env=env,
                                  capture_output=True, text=True,
                                  encoding="utf-8", errors="replace", timeout=120)
    except (OSError, subprocess.SubprocessError):
        return None
    if proc.returncode != 0 or not proc.stdout.strip():
        return None
    return _normcase(proc.stdout.strip())


def _honors_safe_path(python: str) -> bool:
    """その解釈系が **`-P`** を尊重するか（`.ps1` / `.cmd` が使う形そのままで確かめる）。

    シムは `python -P -m <module>` を使う。`-m` は**カレントディレクトリを sys.path の先頭**へ
    置くので、`-P` が無いと呼び出し先に `uapp_dash\\` があるだけで、埋め込んだ `PYTHONPATH` を
    追い越してそちらが動く（実測で再現。exe ではこれは起きない）。
    `-P` は Python 3.11 以降。**バージョン番号で判断せず、その場で挙動を見る**
    （おとりのモジュールを cwd に置き、`-P -m` で見つかってしまわないことを確かめる）。
    """
    try:
        with tempfile.TemporaryDirectory() as neutral:
            probe = Path(neutral) / "uapp_dash_pathprobe.py"
            probe.write_text("pass\n", encoding="ascii")
            env = dict(os.environ)
            env.pop("PYTHONPATH", None)
            env.pop("PYTHONSAFEPATH", None)     # 環境変数の助けを借りない（`-P` だけを見る）
            proc = subprocess.run([python, "-P", "-m", "uapp_dash_pathprobe"],
                                  cwd=neutral, env=env, capture_output=True, timeout=120)
    except (OSError, subprocess.SubprocessError):
        return False
    return proc.returncode != 0        # 見つからない＝カレントディレクトリが外れている


def _this_module() -> str:
    """いま動いている `uapp_dash` の実パス（比較の基準）。"""
    return _normcase(str(Path(__file__).resolve().parent / "__init__.py"))


def _normcase(path: str) -> str:
    try:
        return os.path.normcase(str(Path(path).resolve()))
    except OSError:
        return os.path.normcase(path)


def _package_parent() -> str:
    """`uapp_dash` パッケージを import できるディレクトリ（PYTHONPATH に入れる値）。"""
    return str(Path(__file__).resolve().parent.parent)


def render(module: str, python: str | None = None, *, pythonpath: str | None = None) -> str:
    """`.cmd` シムの中身を作る。python は絶対パスで埋める（PATH 依存を持ち込まない）。"""
    exe = _ascii_path(python or sys.executable, what="Python の実行ファイルのパス")
    if pythonpath:
        block = _PYTHONPATH_LINES.format(
            pythonpath=_escape_percent(_ascii_path(pythonpath, what="PYTHONPATH に入れるパス")))
    else:
        block = ""
    return _TEMPLATE.format(python=_escape_percent(exe), module=module, pythonpath=block)


def render_ps1(module: str, python: str | None = None, *, pythonpath: str | None = None) -> str:
    """`.ps1` シムの中身を作る。

    `.cmd` と違い ASCII 制約は無い（UTF-8 BOM 付きで書けば 5.1 でも正しく読まれる）ので、
    パスは短縮せずそのまま埋める。単引用符の中なので `$` も展開されない
    （`'` 自体は 2 つ重ねてエスケープする）。
    """
    block = _PS_PYTHONPATH_LINES.format(pythonpath=_ps_escape(pythonpath)) if pythonpath else ""
    return _PS_TEMPLATE.format(python=_ps_escape(python or sys.executable),
                               module=module, pythonpath=block)


def _ps_escape(value: str) -> str:
    """PowerShell の単引用符文字列に埋める形（`'` は 2 つ重ねる）。"""
    return str(value).replace("'", "''")


def _powershell_that_cannot_run(script: Path) -> list[str]:
    """この環境で利用できる PowerShell のうち、**その `.ps1` を実行できない**ものの一覧。

    実行ポリシーは環境ごとに違い、`Restricted` / `AllSigned` では未署名スクリプトが動かない
    （会社支給 PC ＝ このシムの想定利用者がまさにそこにいる）。動かない `.ps1` を置くと、
    PowerShell はそれを `.cmd` より優先するので、**今まで動いていた `.cmd` が使われなくなる**
    ＝改善のつもりで壊す。だから実際に走らせて確かめる。

    `-ExecutionPolicy Bypass` は付けない。シムは PATH から素で呼ばれるので、
    **素の条件で動くか**が知りたい（付けて試すと嘘の合格になる）。
    """
    failed = []
    for shell in ("pwsh", "powershell"):
        exe = shutil.which(shell)
        if not exe:
            continue
        try:
            proc = subprocess.run(
                [exe, "-NoProfile", "-NonInteractive", "-File", str(script), "--version"],
                capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=120)
        except (OSError, subprocess.SubprocessError):
            failed.append(shell)
            continue
        if proc.returncode != 0 or not proc.stdout.strip().startswith("uapp-dash "):
            failed.append(shell)
    return failed


def install(directory: Path, *, force: bool = False, python: str | None = None) -> list[Path]:
    """`directory` へシムを作り、作ったパスを返す。

    既存ファイルは `force` が無ければ上書きしない（利用者の別ツールを消さないため）。
    """
    if os.name != "nt":
        raise ShimError(
            "`.cmd` シムは Windows 専用です。POSIX では pip の launcher は"
            "シェルスクリプトなので、この問題は起きません"
            "（必要なら `python -m uapp_dash` を呼ぶ小さなスクリプトを自分で用意してください）")
    directory = Path(directory)
    if directory.exists() and not directory.is_dir():
        raise ShimError(f"出力先がディレクトリではありません: {directory}")

    resolved = directory.resolve()
    # **候補は 1 つに決め打ちしない**。`pip install --user` の launcher は既定 scheme とは
    # 別の Scripts に置かれるので、片方だけ見ると「exe の隣」を許してしまう
    for scripts_dir in _launcher_dirs():
        if resolved == scripts_dir:
            raise ShimError(
                f"exe と同じ場所にはシムを作れません: {directory}。"
                "PATHEXT は同一ディレクトリ内で .exe を .cmd より優先するため、"
                "隣に置いても exe が使われます（隔離されて壊れた exe が居ると詰む）。"
                "**別のディレクトリを指定し、PATH の前方に入れてください**")

    planned = {name: directory / f"{name}.cmd" for name in SHIMS}
    planned_ps = {name: directory / f"{name}.ps1" for name in SHIMS}
    if not force:
        existing = [str(p) for p in list(planned.values()) + list(planned_ps.values())
                    if p.exists()]
        if existing:
            raise ShimError(
                "既にファイルがあります: " + ", ".join(existing) +
                "（上書きするなら --force）")

    exe = python or sys.executable
    # **`python -m` はカレントディレクトリを sys.path の先頭に置く**ので、`-P` が効かない
    # 解釈系ではシムを安全に作れない（呼び出し先に `uapp_dash\` があるだけで別物が動く。
    # exe ではこれは起きない）。バージョン番号で判断せず、その場で走らせて確かめる
    if not _honors_safe_path(exe):
        raise ShimError(
            f"この Python は `-P` を尊重しません: {exe}。"
            "`python -m` はカレントディレクトリを sys.path の先頭に置くため、"
            "呼び出し先に `uapp_dash` という名前のディレクトリがあるとそちらが実行されます"
            "（Python 3.10 以前がこれに当たります）。"
            "**Python 3.11 以降でシムを作り直すか、`python -m uapp_dash …` の読み替えで運用してください**")

    # **書き始める前に**中身を作る（途中で ShimError を出して片方だけ置き換わるのを避ける）
    # 素の解決先が**この実装と一致したときだけ**何も埋めない。
    # 一致しない（import できない／別のコピーを拾う）なら PYTHONPATH で固定する
    pythonpath = None if _resolved_module(exe) == _this_module() else _package_parent()
    bodies = {name: render(module, exe, pythonpath=pythonpath) for name, module in SHIMS.items()}
    ps_bodies = {name: render_ps1(module, exe, pythonpath=pythonpath)
                 for name, module in SHIMS.items()}

    directory.mkdir(parents=True, exist_ok=True)
    # **4 本を稼働中のパスへ直に順番に書かない**。途中で失敗（ロック・I/O エラー）すると
    # 「.cmd は新版・.ps1 は旧版」のような混在が残り、PowerShell と cmd.exe で違う版が
    # 動く。全部を一時名へ書いてから差し替えれば、失敗しても現物には触れずに済む
    # （差し替えそのものは 4 回の rename なので、露出する窓はごく短い）
    staged: list[tuple[Path, Path]] = []      # (一時ファイル, 最終パス)
    try:
        for name in SHIMS:
            # 改行は CRLF（cmd の作法）。ASCII のみなので encoding は問題にならない
            tmp = planned[name].with_name(f"{planned[name].name}.tmp{os.getpid()}")
            tmp.write_text(bodies[name], encoding="ascii", newline="\r\n")
            staged.append((tmp, planned[name]))
        for name in SHIMS:
            # **UTF-8 BOM**。Windows PowerShell 5.1 は BOM が無いと非 ASCII を誤って読む
            tmp = planned_ps[name].with_name(f"{planned_ps[name].name}.tmp{os.getpid()}")
            tmp.write_text(ps_bodies[name], encoding="utf-8-sig", newline="\r\n")
            staged.append((tmp, planned_ps[name]))
    except OSError:
        for tmp, _ in staged:
            tmp.unlink(missing_ok=True)
        raise

    # **差し替えの途中で失敗したら元へ戻す**。`os.replace` を順に流すだけだと、3 本目で
    # ロック・権限エラーになったときに「先頭 2 本は新版・残りは旧版」が残り、PowerShell と
    # cmd.exe で違う版が動く。旧内容を控えておき、失敗したら書き戻す
    previous = {p: p.read_bytes() for _, p in staged if p.exists()}
    written = []
    try:
        for tmp, final in staged:
            os.replace(tmp, final)
            written.append(final)
    except OSError as exc:
        rolled_back = True
        for final in written:                # 差し替え済みを旧内容へ戻す
            try:
                if final in previous:
                    final.write_bytes(previous[final])
                else:
                    final.unlink(missing_ok=True)   # 元から無かったものは消す
            except OSError:
                rolled_back = False
        for tmp, _ in staged:
            tmp.unlink(missing_ok=True)      # 中途半端な一時ファイルを残さない
        state = ("元の状態へ戻しました" if rolled_back else
                 "**元へ戻すことにも失敗したので、新旧が混ざった状態です**"
                 "（PowerShell は `.ps1` を、cmd.exe は `.cmd` を使うので別の版が動きえます）")
        raise ShimError(
            f"シムの差し替えに失敗しました: {exc}。{state}。"
            "原因（ファイルのロック・権限）を解いてから `install-shims --force` をやり直し、"
            "`uapp-dash doctor` で版が揃ったことを確かめてください") from exc

    # **実行ポリシーで `.ps1` が動かない環境がある**（会社支給 PC＝まさに想定利用者）。
    # 動かない `.ps1` を置くと、PowerShell はそれを優先して**今まで動いていた `.cmd` を
    # 使わなくなる**＝改善のつもりで壊す。走らせて確かめ、駄目なら置かない
    blocked = _powershell_that_cannot_run(planned_ps["uapp-dash"])
    if blocked:
        for name in SHIMS:
            planned_ps[name].unlink(missing_ok=True)
            written.remove(planned_ps[name])
    return written


def _launcher_dirs() -> list[Path]:
    """pip が launcher exe を置きうる場所（同じ場所への生成を止めるために見る）。

    **既定 scheme と `--user` scheme の両方**を返す。SETUP は失敗時の手として
    `pip install --user .` を案内しており、その launcher は既定 scheme には置かれない。
    """
    dirs: list[Path] = []
    schemes: list[str | None] = [None]
    try:
        schemes.append(sysconfig.get_preferred_scheme("user"))
    except (KeyError, ValueError, AttributeError):
        pass
    for scheme in schemes:
        try:
            raw = sysconfig.get_path("scripts") if scheme is None \
                else sysconfig.get_path("scripts", scheme)
        except (KeyError, ValueError):
            continue
        if not raw:
            continue
        try:
            path = Path(raw).resolve()
        except OSError:
            continue
        if path not in dirs:
            dirs.append(path)
    return dirs


def _launcher_dir() -> Path | None:
    """既定 scheme の launcher 置き場（後方互換。判定には `_launcher_dirs` を使うこと）。"""
    dirs = _launcher_dirs()
    return dirs[0] if dirs else None
